# Generated by Django 5.1.4 on 2024-12-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('picture', models.ImageField(default=False, upload_to='owner_img')),
            ],
        ),
    ]
