# Generated by Django 5.1.4 on 2024-12-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravailability',
            options={'verbose_name': 'Car Availability', 'verbose_name_plural': 'Car Availabilities'},
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
