# Generated by Django 5.1.4 on 2024-12-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_caravailability_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravailability',
            options={'verbose_name': 'Available Car'},
        ),
    ]
