# Generated by Django 5.1.4 on 2024-12-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_caravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravailability',
            options={'verbose_name': 'Active Cars'},
        ),
    ]
