# Generated by Django 5.1.4 on 2024-12-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_caravailability_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravailability',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
