# Generated by Django 5.1.4 on 2024-12-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_caravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caravailability',
            unique_together={('car', 'date')},
        ),
    ]
